Repository wanted-team2/3week_SearchFilter, pull requests merged in 2022-02, with the labels that each got.

#6 ✨ Feat: TagList 구현
  src/components/base/Tag/Style.ts
  src/components/base/Tag/Tag.tsx
  src/components/base/index.ts
  src/components/domain/TagList/Style.ts
  src/components/domain/TagList/TagList.tsx
  src/components/domain/index.ts
  src/styles/theme.ts
  src/types/Item.ts
  src/types/index.ts
Labels: Feat

#7 ✨ Feat: Header, ItemBox, MainBox 구현
  src/components/base/EmptyBox/EmptyBox.tsx
  src/components/base/EmptyBox/Style.ts
  src/components/base/Header/Header.tsx
  src/components/base/Header/Style.ts
  src/components/base/ItemBox/ItemBox.tsx
  src/components/base/ItemBox/Style.ts
  src/components/base/MainBox/MainBox.tsx
  src/components/base/MainBox/Style.ts
  src/components/base/index.ts
  src/hooks/useAsync/index.ts
  src/styles/globalStyles.ts
  src/styles/theme.ts
Labels: UI, Fix, Feat

#16 ✨ Feat: debounce 적용
  package.json
  src/components/base/EmptyBox/EmptyBox.tsx
  src/components/base/Header/Header.tsx
  src/components/base/Input/Input.tsx
  src/pages/Main/Main.tsx
  yarn.lock
Labels: Feat

#23 ✨ Feat: Reset버튼 추가
  src/components/base/Input/Input.tsx
  src/components/base/Input/Style.ts
  src/pages/Main/Main.tsx
Labels: Fix, Feat

#25 ✨ Feat: Tag버튼 toggle기능 추가
  src/components/base/Tag/Tag.tsx
  src/components/domain/MainBox/MainBox.tsx
  src/components/domain/PaginationWrapper/PaginationWrapper.tsx
  src/components/domain/TagList/TagList.tsx
  src/pages/Main/Main.tsx
Labels: Feat

#28 💄 UI: 레이아웃 수정
  src/components/base/Input/Input.tsx
  src/components/base/Input/Style.ts
  src/components/base/ItemBrandBtn/ItemBrandBtn.tsx
  src/components/base/ItemBrandBtn/Style.ts
  src/components/base/ResetBtn/ResetBtn.tsx
  src/components/base/ResetBtn/Style.ts
  src/components/base/index.ts
  src/components/domain/Header/Header.tsx
  src/components/domain/Header/Style.ts
  src/components/domain/MainBox/Style.ts
  src/components/domain/PaginationWrapper/Style.ts
  src/components/domain/index.ts
  src/pages/Main/Main.tsx
  src/pages/Main/Style.ts
Labels: UI, Fix
